version: '2'
services:
    agiflex-app:
        image: agiflex
        external_links:
            - agiflex-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/agiflex?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    agiflex-mysql:
        extends:
            file: mysql.yml
            service: agiflex-mysql
